car_service/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('index/', views.index, name="index"),
    path('cars/', views.cars, name='cars'),
    path('car/<int:pk>/', views.car_detail, name='car_detail'),
    path('orders/', views.OrderListView.as_view(), name='orders'),
    path('order/<int:order_id>/', views.order_detail, name='order_detail'),
    path('search/', views.search_results, name='search_results'),
    path('', views.index, name='index'),

    path('myorders/', views.ServiceOrderByUserListView.as_view(), name="current-orders"),
    path('register/', views.register_user, name="register-url"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from car_service.views import index
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('car_service/', include('car_service.urls')),
    path('', RedirectView.as_view(url='car_service/', permanent=True)),
    path('tinymcre', include('tinymce.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

urlpatterns += [
    path("accounts/", include('django.contrib.auth.urls')),
]

car_service/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date
import uuid
from tinymce.models import HTMLField


class CarModel(models.Model):
    brand = models.CharField('Brand', max_length=100)
    model = models.CharField('Model', max_length=100)
    year = models.IntegerField('Year')
    engine = models.CharField('Engine', max_length=100)

    class Meta:
        ordering = ['brand', 'model', ]

    def __str__(self):
        return f'{self.brand} {self.model} | {self.year}'


class Car(models.Model):
    license_plate = models.CharField('License plate', max_length=7)
    vin = models.CharField('VIN', max_length=17)
    client = models.CharField('Client', max_length=100)
    car_model = models.ForeignKey(CarModel, on_delete=models.SET_NULL, null=True)
    image = models.ImageField(upload_to='car_images/', null=True, blank=True)
    # description = models.TextField('Description', null=True, blank=True, max_length=300)
    description = HTMLField()

    class Meta:
        ordering = ['client', 'car_model']

    def __str__(self):
        return f'{self.client} {self.car_model}'


class Service(models.Model):
    name = models.CharField('Name', max_length=50)
    price = models.FloatField('Price, EUR')

    class Meta:
        ordering = ['name', ]

    def __str__(self):
        return f'{self.name} {round(self.price)} EUR'


class Order(models.Model):
    date = models.DateField('Date', null=True, blank=True)
    car = models.ForeignKey(Car, on_delete=models.SET_NULL, null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    ORDER_STATUS = (
        ('p', 'Processing'),
        ('o', 'Ordered'),
        ('s', 'In service'),
        ('c', 'Completed'),
        ('t', 'Taken back by customer')
    )
    status = models.CharField(max_length=1, choices=ORDER_STATUS,
                              blank=True, default='p')

    @property
    def order_total_price(self):
        order_rows = self.order_row.all()
        total_price = sum(row.total_price for row in order_rows)
        return round(total_price)

    @property
    def order_rows(self):
        return ', '.join(str(el) for el in self.order_row.all())

    @property
    def is_overdue(self):
        if self.date and date.today() > self.date:
            return True
        else:
            return False

    def __str__(self):
        return f'{self.car}'



class OrderRow(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique service ID', editable=False)
    amount = models.IntegerField('Amount')
    service = models.ForeignKey(Service, on_delete=models.SET_NULL, null=True, related_name='service')
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, related_name='order_row')

    @property
    def total_price(self):
        total__for_amount = self.service.price * self.amount
        return total__for_amount

    @property
    def service_name(self):
        return self.service.name

    @property
    def client_car(self):
        return self.order.car

    @property
    def order_date(self):
        return self.order.date

    def __str__(self):
        return f'{self.amount} orders of {self.service.name} for total {self.total_price} EUR'

car_service/views.py
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Car, Order, Service, OrderRow
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages


def index(request):
    visit_count = request.session.get('visit_count', 0)
    visit_count += 1
    request.session['visit_count'] = visit_count

    total_cars = Car.objects.count()
    total_orders = Order.objects.count()
    total_services = Service.objects.count()

    context = {
        'total_cars': total_cars,
        'total_orders': total_orders,
        'total_services': total_services,
        'visit_count': visit_count,
    }
    return render(request, 'index.html', context)


def cars(request):
    car_list = Car.objects.all()
    cars_per_page = 6
    paginator = Paginator(car_list, cars_per_page)
    page = request.GET.get('page')
    try:
        cars = paginator.page(page)
    except PageNotAnInteger:
        cars = paginator.page(1)
    except EmptyPage:
        cars = paginator.page(paginator.num_pages)
    return render(request, 'cars.html', {'cars': cars})


def car_detail(request, pk):
    car = get_object_or_404(Car, pk=pk)
    return render(request, 'car_detail.html', {'car': car})


class OrderListView(generic.ListView):
    model = Order
    context_object_name = "orders"
    template_name = "orders.html"
    paginate_by = 5


class ServiceOrderByUserListView(LoginRequiredMixin, generic.ListView):
    model = Order
    template_name = 'user_orders.html'
    context_object_name = 'orders'

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user).order_by('date')


def order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    order_rows = order.order_row.all()
    return render(request, 'order_detail.html', {'order': order, 'order_rows': order_rows})


def search_results(request):
    query_text = request.GET.get("search_text", "")

    car_results = Car.objects.filter(
        Q(client__icontains=query_text) |
        Q(car_model__brand__icontains=query_text) |
        Q(car_model__model__icontains=query_text) |
        Q(license_plate__icontains=query_text) |
        Q(vin__icontains=query_text)
    )

    context = {
        "car_results": car_results,
        "query_text": query_text,
    }

    return render(request, "search_results.html", context=context)

@csrf_protect
def register_user(request):
    if request.method != "POST":
        return render(request, 'registration/registration.html')
    username = request.POST["username"]
    email = request.POST["email"]
    password = request.POST["password"]
    password2 = request.POST["password2"]

    if password != password2 :
        messages.error(request, "Passwords do not match!")

    if User.objects.filter(username=username).exists():
        messages.error(request, f"Username {username} is already taken!")

    if User.objects.filter(email=email).exists():
        messages.error(request, f"E-mail {email} is already being used!")

    if messages.get_messages(request):
        return redirect('register-url')

    User.objects.create_user(username=username, email=email, password=password)
    messages.success(request, f"User {username} created!")
    return redirect('login')

car_service/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
    <title>Car service</title>
    {% endblock %}
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
            integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
            crossorigin="anonymous"
    />
    <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
</head>
<body>
<!-- Navigation -->

<nav
        class="navbar navbar-expand-lg navbar-light bg-light static-top mb-5 shadow"
>
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor"
                 class="bi bi-car-front-fill" viewBox="0 0 16 16">
                <path d="M2.52 3.515A2.5 2.5 0 0 1 4.82 2h6.362c1 0 1.904.596 2.298 1.515l.792 1.848c.075.175.21.319.38.404.5.25.855.715.965 1.262l.335 1.679q.05.242.049.49v.413c0 .814-.39 1.543-1 1.997V13.5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-1.338c-1.292.048-2.745.088-4 .088s-2.708-.04-4-.088V13.5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-1.892c-.61-.454-1-1.183-1-1.997v-.413a2.5 2.5 0 0 1 .049-.49l.335-1.68c.11-.546.465-1.012.964-1.261a.8.8 0 0 0 .381-.404l.792-1.848ZM3 10a1 1 0 1 0 0-2 1 1 0 0 0 0 2m10 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2M6 8a1 1 0 0 0 0 2h4a1 1 0 1 0 0-2zM2.906 5.189a.51.51 0 0 0 .497.731c.91-.073 3.35-.17 4.597-.17s3.688.097 4.597.17a.51.51 0 0 0 .497-.731l-.956-1.913A.5.5 0 0 0 11.691 3H4.309a.5.5 0 0 0-.447.276L2.906 5.19Z"/>
            </svg>
            Car service shop!</a
        >
        <button
                class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbarResponsive"
                aria-controls="navbarResponsive"
                aria-expanded="false"
                aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="#">
                    <svg class="bi bi-person"
                         width="1.5em"
                         height="1.5em"
                         viewBox="0 0 16 16"
                         fill="currentColor"
                         xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1
                            1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168
                            1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8
                            7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z" clip-rule="evenodd"/>
                    </svg>
                    {{ user }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}?next=/car_service">Logout</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'current-orders' %}">My orders</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}?=next{{ request.path }}">Login</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'register-url' %}?=next{{ request.path }}">Register</a>
                </li>
                {% endif %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">Main menu</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cars' %}">Cars</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'orders' %}">Orders</a>
                </li>
            </ul>

            <form
                    class="form-inline my-2 my-lg-0"
                    action="{% url 'search_results' %}"
                    method="get"
            >
                <input
                        class="form-control mr-sm-2"
                        type="search"
                        placeholder="Search"
                        aria-label="Search"
                        name="search_text"
                />
                <button class="btn btn-outline-info my-2 my-sm-0" type="submit">
                    Search
                </button>
            </form>
        </div>
    </div>
</nav>

{% for message in messages %}
<div class="alert alert-{% if message.tags == 'success' %}success{% else %}danger{% endif %}" role="alert">
    {{ message }}
</div>
{% endfor %}

<div class="container">{% block content %}{% endblock %}</div>

<script
        src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"
></script>
<script
        src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"
></script>
<script
        src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"
></script>
</body>
</html>

car_service/templates/car_detail.html
{% extends 'base.html' %}

{% block header %}Car Detail{% endblock %}

{% block content %}
    <h2>Car Details</h2>
    <ul>
        <div class="card mb-4 shadow-sm">
            <div class="card-body">
                {% if car.image %}
                    <img src="{{ car.image.url }}" class="card-img-top" style="max-width: 100%; height: 300px;"/>
                {% endif %}
            </div>
        </div>
        <li><strong>Description:</strong> {{ car.description | safe}} </li>
        <hr/>
        <li><strong>Brand:</strong> {{ car.car_model.brand }}</li>
        <li><strong>Model:</strong> {{ car.car_model.model }}</li>
        <li><strong>Year:</strong> {{ car.car_model.year }}</li>
        <li><strong>License Plate:</strong> {{ car.license_plate }}</li>
        <li><strong>VIN:</strong> {{ car.vin }}</li>
        <li><strong>Client:</strong> {{ car.client }}</li>
    </ul>
    {% if car.order_set.exists %}
        <h2>Orders</h2>
        <ul>
            {% for order in car.order_set.all %}
                <li>
                    <a href="{% url 'order_detail' order_id=order.id %}">View orders</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No orders for this car.</p>
    {% endif %}
    <p><a href="{% url 'cars' %}">Back to Cars</a></p>
{% endblock %}

car_service/templates/cars.html
{% extends 'base.html' %}
{% load static %}

{% block header %}Cars{% endblock %}


{% block content %}
    <div class="row">
        {% for car in cars %}
            <div class="col-sm-6 col-md-4 d-flex align-items-stretch">
                <div class="card mb-4 shadow-sm">
                    {% if car.image %}
                    <img src="{{ car.image.url }}" class="card-img-top"/>
                    {% else %}
                    <img src="{% static 'img/no-image.png' %}" class="card-img-top"/>
                    {% endif %}
                    <div class="card-body">
                        <p class="card-text"><a href="{% url 'car_detail' car.id %}">{{ car.car_model.brand }}
                            {{ car.car_model.model }} {{ car.license_plate }}</a></p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="pagination">
        <span class="step-links">
            {% if cars.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ cars.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ cars.number }} of {{ cars.paginator.num_pages }}.
            </span>

            {% if cars.has_next %}
                <a href="?page={{ cars.next_page_number }}">next</a>
                <a href="?page={{ cars.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock %}

car_service/templates/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Home page</h1>

<h2>Statistics</h2>
<p>Total Cars: {{ total_cars }}</p>
<p>Total Orders: {{ total_orders }}</p>
<p>Total Services: {{ total_services }}</p>
<p>{{ user }} visit count: {{ visit_count }}</p>

{% endblock %}

car_service/templates/order_detail.html
{% extends 'base.html' %}

{% block header %}Order Detail{% endblock %}

{% block content %}
    <h2>Order Information</h2>
    <ul>
        <li><strong>Date:</strong> {{ order.date }}</li>
        <li><strong>Car:</strong> <a href="{% url 'car_detail' pk=order.car.id %}">{{ order.car.car_model.brand }} {{ order.car.car_model.model }}</a></li>
        <li><strong>Total Price:</strong> {{ order.order_total_price|floatformat:2 }} EUR</li>
    </ul>

    <h2>Services</h2>
    <ul>
        {% for order_row in order_rows %}
            <li>
                {{ order_row.service_name }} |
                <strong>Amount:</strong> {{ order_row.amount }} |
                <strong>Total Price:</strong> {{ order_row.total_price|floatformat:2 }} EUR
            </li>
        {% endfor %}
    </ul>

    <p><a href="{% url 'orders' %}">Back to Orders</a></p>
{% endblock %}

car_service/templates/orders.html
{% extends 'base.html' %}

{% block header %}Orders{% endblock %}

{% block content %}

<h2>List of Orders</h2>
<ul>
    {% for order in page_obj %}
        <li>
            <a href="{% url 'order_detail' order.id %}">
                {{ order.car.client }} - {{ order.car.car_model.brand }}
                {{ order.car.car_model.model }} {{ order.car.license_plate }}<br>
            </a>
        </li>
        <br>
    {% endfor %}
</ul>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; First</a>
            <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}

car_service/templates/search_results.html
{% extends 'base.html' %}

{% block header %}Search Results{% endblock %}

{% block content %}

<h2>Search Results for '{{ query_text }}'</h2>

{% if car_results %}
<ul>
    {% for car in car_results %}
    <li>
        <a href="{% url 'car_detail' car.id %}">
            {{ car.client }} - {{ car.car_model.brand }} {{ car.car_model.model }} ({{ car.license_plate }})
        </a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>We didn't find anything... Please try again</p>
{% endif %}
{% endblock %}

car_service/templates/user_orders.html
{% extends 'base.html' %}

{% block header %}Orders{% endblock %}

{% block content %}
<h1>My orders:</h1>
{% if orders %}
    <ul>
        {% for order in orders %}
            <li class="{% if order.is_overdue %}text-danger{% else %}text-success{% endif %}">
                <a href="{% url 'order_detail' order.id %}">
                {{ order.car.car_model.brand }} {{ order.car.car_model.model }}
                </a>
                {% if order.date %}
                    {{ order.date }}
                {% else %}
                    No set date
                {% endif %}
                <p class="{% if order.status == 'p' %} text-danger
                          {% elif order.status == 't' %} text-muted
                          {% elif order.status == 'c' %} text-success
                          {% else %} text-warning
                          {% endif %} "><strong>{{ order.get_status_display }}</strong></p>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No current orders</p>
{% endif %}
{% endblock %}